### ISSUE TITLE
/ zero

### ISSUE THREAD

**Issue by nicobresseleers** [notaus123/dbus-solarlog#1]
Hi,

integration worked for a short while... now it crashes:

When i start manual:

root@raspberrypi2:/data/dbus-solarlog#
root@raspberrypi2:/data/dbus-solarlog# python /data/dbus-solarlog/dbus-solarlog.py
Connected to dbus, and switching over to gobject.MainLoop() (= event based)
Issues querying **Solarlog -ERROR : division by zero**
^CTraceback (most recent call last):
  File "/data/dbus-solarlog/dbus-solarlog.py", line 275, in <module>
    mainloop.run()
  File "/usr/lib/python3.8/site-packages/gi/overrides/GLib.py", line 497, in run
    super(MainLoop, self).run()
  File "/usr/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/usr/lib/python3.8/site-packages/gi/_ossighelper.py", line 251, in register_sigint_fallback
    signal.default_int_handler(signal.SIGINT, None)
KeyboardInterrupt

No clue where the 0 comes from... 

anything else you need?

nico

**Comment by nicobresseleers** [comment]
error disappeared .. no more errors. i guess we can close?
